media: media
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    view:
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Categories, name: categories, widget: list, field: {label: Category, name: category, widget: string}}
        - {label: Author, name: author, widget: string, required: false}
        - {label: Body, name: body, widget: markdown}
        - {label: Slug, name: slug, widget: string, required: false}
        - {label: Description, name: description, widget: string, required: false}
        - {label: Draft, name: draft, widget: boolean, default: false, required: false}
        - {label: Pin, name: pin, widget: boolean, default: false, required: false}
        - {label: Publish Date, name: pubDate, widget: datetime, format: YYYY-MM-DD}
        - {label: Modification Date, name: modDate, widget: datetime, format: YYYY-MM-DD, required: false}
