media: media
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    view: 
      fields: ["title","categories","author","body","slug","description","draft","pin", "pubDate","modDate"]
    fields:
      - name: title
        label: Title
        type: string
      - name: categories
        label: Categories
        type: select
        options:
          values: [ Poesía, Cerebro, Manifiesto ]
          multiple: true
          creatable: true
      - name: author
        label: Author
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: slug
        label: Slug
        type: string
      - name: description
        label: Description
        type: string
      - name: draft
        label: Draft
        type: boolean
      - name: pin
        label: Pin
        type: boolean
      - name: pubDate
        label: Publish Date
        type: date
        options:
          format: yyyy-MM-dd
      - name: modDate
        label: Modification Date
        type: date
        options:
          format: yyyy-MM-dd