backend:
  name: github
  branch: add-sveltia-cms
  repo: carafelix/verse-is-dead # change this to your repo
  site_domain: elversomurio.cl # change this to your domain
  base_url: https://elversomurio.cl # change this to your prod URL
  auth_endpoint: oauth # the oauth route provided by the integration

public_folder: public/images/uploads
media_folder: static/

collections:
  - label: Blog
    name: blog
    folder: src/content/posts
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Featured Image, name: thumbnail, widget: image}
      - {label: Body, name: body, widget: markdown}
